// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChc5MG66A07-wLeDyyI2WAmdxd1Br8-Qs',
    appId: '1:995533624756:web:7b6bbae1f91fc2968a8ee1',
    messagingSenderId: '995533624756',
    projectId: 'iot-kolam-ikan',
    authDomain: 'iot-kolam-ikan.firebaseapp.com',
    storageBucket: 'iot-kolam-ikan.firebasestorage.app',
    measurementId: 'G-293FZN4J74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNrIQyX9DlV2gP8hl5AQrT_Rwm6QUgENE',
    appId: '1:995533624756:android:a646e4f4b0dfc6be8a8ee1',
    messagingSenderId: '995533624756',
    projectId: 'iot-kolam-ikan',
    storageBucket: 'iot-kolam-ikan.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI68vbzdI_cyQurYFctBUtN0La_LsIlOc',
    appId: '1:995533624756:ios:e981de29dc0294188a8ee1',
    messagingSenderId: '995533624756',
    projectId: 'iot-kolam-ikan',
    storageBucket: 'iot-kolam-ikan.firebasestorage.app',
    iosBundleId: 'com.example.iotKolamikan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI68vbzdI_cyQurYFctBUtN0La_LsIlOc',
    appId: '1:995533624756:ios:e981de29dc0294188a8ee1',
    messagingSenderId: '995533624756',
    projectId: 'iot-kolam-ikan',
    storageBucket: 'iot-kolam-ikan.firebasestorage.app',
    iosBundleId: 'com.example.iotKolamikan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChc5MG66A07-wLeDyyI2WAmdxd1Br8-Qs',
    appId: '1:995533624756:web:f1ed0f066d5371128a8ee1',
    messagingSenderId: '995533624756',
    projectId: 'iot-kolam-ikan',
    authDomain: 'iot-kolam-ikan.firebaseapp.com',
    storageBucket: 'iot-kolam-ikan.firebasestorage.app',
    measurementId: 'G-RP4E2KQG31',
  );
}
